name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # support the last three Go release versions
        go_version:
          - 1.21
          - 1.22
          - 1.23
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
